language: objective-c
os: osx
osx_image: xcode7
podfile: PagingViewExample/Podfile
cache: cocoapods
before_install:
  - gem install cocoapods
  - pod install --project-directory=PagingViewExample
script:
  - xcodebuild -workspace ./PagingViewExample/PagingViewExample.xcworkspace -scheme PagingViewExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' test
